### ISSUE TITLE
Implement Delete & Download for Files

### ISSUE THREAD

**Issue by austinlxx** [TheParrotsAreComing/PAS#113]
Functions **Delete** and **Download** have not been implemented for files.

Files functionality extends to cats, adopters, and fosters.
- [Cats] 
- [Adopters] 
- [Fosters]

**Comment by theRonLewis** [comment]
Delete looks OK for cats - but confirm dialogue needs updated text

**Comment by theRonLewis** [comment]
Download for all files needs to be implemented

**Comment by theRonLewis** [comment]
Delete is wonky, research alot

**Comment by theRonLewis** [comment]
- [Cats] 
- [Adopters] 
- [Fosters]

**Comment by theRonLewis** [comment]
implemented for cats, will work on adopters/fosters soon

**Comment by erykwong** [comment]
Awesome function Ron!
