### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by ericbollinger** [TheParrotsAreComing/PAS#129]
- [x] Cats
- [x] Adopters
- [x] Fosters
- [x] Adoption Events
- [x] Volunteers

**Comment by vanessacruz** [comment]
Can now sort for deleted cats, adopters, fosters, and volunteers.
Not sure how adoption events have to be sorted.

**Comment by robertrico** [comment]
I think it'd be sufficient to implement sort by date and name at minimum. Any other sort filter will probably be explicitly asked for by the client

**Comment by theRonLewis** [comment]
I think until they even start using it, lets just get the "Current"/"Upcoming"/"Past" tabs working. I'll start on that.
