### ISSUE TITLE
When no file is uploaded for medical history

### ISSUE THREAD

**Issue by robertrico** [TheParrotsAreComing/PAS#133]
And you try to download. it breaks.

**Comment by theRonLewis** [comment]
@austinlxx In order for us to do this, and also give us a good level of functionality for other things that use this type of menu, I think we need a way to disable the buttons. That way if no file is there, we can disable it, and it'll make the button look faded, etc. For other buttons, there is an "active" class that we add or remove if the button can be pressed and cause an action. Can we get something similar for this? This would be for Cat medical histories, individual file lists on cats/adopters/fosters/etc (not photos, altho the photos have the other buttons w/the actve class just fyi)

**Comment by austinlxx** [comment]
To make one of those buttons _disabled_ at any view, simply add **disabled** to it, like so:

- [ ] left medical-data-action w-inline-block

- [ ] left **disabled** medical-data-action w-inline-block
